### ISSUE TITLE
Broken project: projects/briey/vga

### ISSUE THREAD

**Issue by roman3017** [SpinalHDL/VexRiscvSocSoftware#2]
It seems that some recent changes broke the build of the vga project:

```bash
VexRiscvSocSoftware/projects/briey/vga$ RISCV_NAME=riscv32-unknown-elf RISCV_PATH=/opt/riscv32i make
/opt/riscv32i/bin/riscv32-unknown-elf-gcc -march=rv32i  -mabi=ilp32 -g3 -O0  -MD -fstrict-volatile-bitfields  -o build/vga.elf build/src/main.o build/src/crt.o -march=rv32i  -mabi=ilp32 -nostdlib -lgcc -mcmodel=medany -nostartfiles -ffreestanding -Wl,-Bstatic,-T,../libs/linker.ld,-Map,build/vga.map,--print-memory-usage 
Memory region         Used Size  Region Size  %age Used
       onChipRam:        2384 B         4 KB     58.20%
           sdram:      615488 B        64 MB      0.92%
build/src/main.o: In function `main':
VexRiscvSocSoftware/projects/briey/vga/src/main.c:27: undefined reference to `memcpy'
collect2: error: ld returned 1 exit status
../../../resources/subproject.mk:45: recipe for target 'build/vga.elf' failed
make: *** [build/vga.elf] Error 1

```
It worked for me few days ago.

**Comment by Dolu1990** [comment]
Hi,

I reworked the makefiles to avoid having system call leaks into the generated binaries from the precompilated c libaries, that why now you have memcpy isn't by default included.

You can add the following line into your makefile, it will solve it. 
LDFLAGS += -lc

**Comment by roman3017** [comment]
Thank you very much, it works. I can compile vga project with:

```
RISCV_NAME=riscv32-unknown-elf RISCV_PATH=/opt/riscv32i LDFLAGS=-lc make
```

**Comment by roman3017** [comment]
I can build vga project now but it does not run after this commit:
https://github.com/SpinalHDL/VexRiscvSocSoftware/commit/f789f1eb241a46cc939cbb377d4cfc2b8eebdb19
Any commit before that works for me.

```gdb
(gdb) monitor reset halt
JTAG tap: fpga_spinal.bridge tap/device found: 0x10001fff (mfg: 0x7ff (<invalid>), part: 0x0001, ver: 0x1)
(gdb) load              
Loading section .memory, size 0x404 lma 0x40000000
Loading section .rodata, size 0x60 lma 0x40000404
Loading section .data, size 0x4 lma 0x40000464
Loading section .vector, size 0x150 lma 0x80000000
Start address 0x80000000, load size 1464
Transfer rate: 5 KB/sec, 366 bytes/write.
(gdb) cont              
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x0000010c in ?? ()
```

Please note the final address 0x0000010c is out of the range and cannot be disassembled.

**Comment by Dolu1990** [comment]
Have you regenerated the bitstream of the FPGA from the recent briey version ?
I have done some memory remapping. It is very likely the issue.

**Comment by Dolu1990** [comment]
I just tested, and it's working in simulation, so basicaly the onChipRam is not mapped at 0x80000000 instead of  0x00000000. Just regenerate all the hardware side, and it should be fine :)

**Comment by roman3017** [comment]
You are right, after pulling and rebuilding the latest SpinalHDL the vga project got working again. Thank you very much.

**Comment by roman3017** [comment]
Just for completeness, one can load the project binary without gdb connecting to remote target on port 3333 but by connecting to the Open On-Chip Debugger running on port 4444 instead:

```gdb
$ telnet localhost 4444
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
> reset halt
JTAG tap: fpga_spinal.bridge tap/device found: 0x10001fff (mfg: 0x7ff (<invalid>), part: 0x0001, ver: 0x1)
> load_image /local/projects/VexRiscvSocSoftware/projects/briey/vga/build/vga.elf
1128 bytes written at address 0x40000000
336 bytes written at address 0x80000000
downloaded 1464 bytes in 0.380612s (3.756 KiB/s)
> resume 0x80000000
```

I have found this useful when instantiating the processor on Zynq FPGA with openocd running on ARM and not having gdb on ARM to load the code with.
