### ISSUE TITLE
Problem building murax dhrystone example

### ISSUE THREAD

**Issue by robindust-ce** [SpinalHDL/VexRiscvSocSoftware#4]
I have the prebuilt sifive toolchain installed on Ubuntu 20.04  and it is generally working (e.g. building the murax demo project). But when I build the dhrystone  example I get the following errors:

```
/opt/riscv//bin/riscv64-unknown-elf-gcc -fno-inline -fno-common -DPREALLOCATE=1 -DHOST_DEBUG=0 -DMSC_CLOCK -march=rv32i  -mabi=ilp32 -g -O3  -MD -fstrict-volatile-bitfields  -o build/dhrystone.elf build/src/main.o build/src/dhry_1.o build/src/dhry_2.o build/src/crt.o build/src/stdlib.o -lc -lc  -march=rv32i  -mabi=ilp32 -nostdlib -lgcc -mcmodel=medany -nostartfiles -ffreestanding -Wl,-Bstatic,-T,linker.ld,-Map,build/dhrystone.map,--print-memory-usage
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-memcpy.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-memcpy.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-strcmp.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-strcmp.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divsf3.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divsf3.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divdf3.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divdf3.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(div.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(div.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clzsi2.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clzsi2.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clz.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clz.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: build/src/dhry_1.o: in function `main2':
/home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:158: undefined reference to `__mulsi3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:255: undefined reference to `__floatsisf'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:256: undefined reference to `__extendsfdf2'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:257: undefined reference to `__muldf3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:258: undefined reference to `__truncdfsf2'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:261: undefined reference to `__floatsisf'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:262: undefined reference to `__fixsfsi'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:263: undefined reference to `__floatsisf'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:265: undefined reference to `__subsf3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:265: undefined reference to `__mulsf3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:269: undefined reference to `__fixsfsi'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: build/dhrystone.elf(.text): relocation ".L15+0x0 (type R_RISCV_RVC_JUMP)" goes out of range
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divsf3.o): file class ELFCLASS64 incompatible with ELFCLASS32
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: final link failed: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [../../../resources/subproject.mk:45: build/dhrystone.elf] Error 1
```

From my understanding this might be because "rv32i-ilp32" is not present in the prebuilt toolchain's multilib. When I change the compiler flag to -march=rv32ic (which is present) it builds succesfully.

Could you please guide me on how to approach this? Do I need to rebuild the toolchain with added multilibs from source? Why does this issue occur when building the dhrystone example but not when building the demo?

Thank you!

**Comment by robindust-ce** [comment]
I have the prebuilt sifive toolchain installed on Ubuntu 20.04  and it is generally working (e.g. building the murax demo project). But when I build the dhrystone  example I get the following errors:

/opt/riscv//bin/riscv64-unknown-elf-gcc -fno-inline -fno-common -DPREALLOCATE=1 -DHOST_DEBUG=0 -DMSC_CLOCK -march=rv32i  -mabi=ilp32 -g -O3  -MD -fstrict-volatile-bitfields  -o build/dhrystone.elf build/src/main.o build/src/dhry_1.o build/src/dhry_2.o build/src/crt.o build/src/stdlib.o -lc -lc  -march=rv32i  -mabi=ilp32 -nostdlib -lgcc -mcmodel=medany -nostartfiles -ffreestanding -Wl,-Bstatic,-T,linker.ld,-Map,build/dhrystone.map,--print-memory-usage
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-memcpy.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-memcpy.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-strcmp.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/lib/libc.a(lib_a-strcmp.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divsf3.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divsf3.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divdf3.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divdf3.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(div.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(div.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clzsi2.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clzsi2.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clz.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(_clz.o)
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: build/src/dhry_1.o: in function `main2':
/home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:158: undefined reference to `__mulsi3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:255: undefined reference to `__floatsisf'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:256: undefined reference to `__extendsfdf2'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:257: undefined reference to `__muldf3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:258: undefined reference to `__truncdfsf2'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:261: undefined reference to `__floatsisf'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:262: undefined reference to `__fixsfsi'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:263: undefined reference to `__floatsisf'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:265: undefined reference to `__subsf3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:265: undefined reference to `__mulsf3'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/robin/SpinalHDL/VexRiscvSocSoftware/projects/murax/dhrystone/src/dhry_1.c:269: undefined reference to `__fixsfsi'
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: build/dhrystone.elf(.text): relocation ".L15+0x0 (type R_RISCV_RVC_JUMP)" goes out of range
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: /opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(divsf3.o): file class ELFCLASS64 incompatible with ELFCLASS32
/opt/riscv/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: final link failed: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [../../../resources/subproject.mk:45: build/dhrystone.elf] Error 1

Could you please guide me on how to approach this? Do I need to rebuild a adapted toolchain from source?

Thank you!

**Comment by Dolu1990** [comment]
Hi ^^
I think that's because dhrystone use some division which require some library to be emulated in software.

An alternative may be to use the xpack : 

https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/

```
# RISC-V toolchain
VERSION=8.3.0-1.2
mkdir -p ~/opt
cd ~/opt
wget https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v$VERSION/xpack-riscv-none-embed-gcc-$VERSION-linux-x64.tar.gz
tar -xvf xpack-riscv-none-embed-gcc-$VERSION-linux-x64.tar.gz
rm xpack-riscv-none-embed-gcc-$VERSION-linux-x64.tar.gz
mv xpack-riscv-none-embed-gcc-$VERSION xpack-riscv-none-embed-gcc
echo 'export PATH=~/opt/xpack-riscv-none-embed-gcc/bin:$PATH' >> ~/.bashrc
export PATH=~/opt/xpack-riscv-none-embed-gcc/bin:$PATH
```

(you will have to update https://github.com/SpinalHDL/VexRiscvSocSoftware/blob/master/resources/gcc.mk#L5 to match)

**Comment by Dolu1990** [comment]
And yes, you are right avout rv32ic i guess

**Comment by robindust-ce** [comment]
Thank you for the quick and helpful response!
